import numpy as np
import os, sys
from scipy.optimize import minimize, root_scalar
from mpl_toolkits.mplot3d import Axes3D
import matplotlib.pyplot as plt
import matplotlib.animation as animation
sys.path.insert(0, 'X:\\Nicola_Gritti\\Repos\\tgmm_quality\\src')
import utils_registration as reg

keys = ['old_id','old_parentid','cell_id','parent_id','lineage','timepoint','X','Y','Z','splitScore']
scale = 2.554

'''
### not corrected data
'''
### load raw data
print('#'*20+'loading cell tracks generated by TGMM')
data_raw = np.loadtxt(os.path.join('GMEMtracking3D_2019_10_14_16_22_2','cell_track_not_corr.txt'))

##### compute cm and center of mass and save the file
# print('#'*20+'computing embryo track (centroid and cm)')
# reg.compute_centroid_and_cm(data_raw,_max=np.max(data_raw[:,keys.index('timepoint')]),
#                           name=os.path.join('GMEMtracking3D_2019_10_14_16_22_2','embryo_track_not_corr.txt'))
##### load file
print('#'*20+'loading embryo track (centroid and cm)')
data = np.loadtxt(os.path.join('GMEMtracking3D_2019_10_14_16_22_2','embryo_track_not_corr.txt'))
centroid = data[:,1:4]
cm = data[:,-3:]

##### make not corrected animation
# reg.make_3d_animation(data_raw,centroid,cm,name='epiboly_not_corrected.mp4',ang=(40,100))

'''
### corrected data
'''
##### correct position file
print('#'*20+'generating file with corrected cell tracks')
reg.correct_pos_file(centroid,cm,data_raw,_max=np.max(data_raw[:,keys.index('timepoint')]),
                          name=os.path.join('GMEMtracking3D_2019_10_14_16_22_2','cell_track_corr.txt'))
##### load new data
print('#'*20+'loading cell tracks corrected')
data_corr = np.loadtxt(os.path.join('GMEMtracking3D_2019_10_14_16_22_2','cell_track_corr.txt'))

##### compute cm and ecnter of mass and save the file
print('#'*20+'computing new embryo track (centroid and cm)')
reg.compute_centroid_and_cm(data_corr,_max=np.max(data_corr[:,keys.index('timepoint')]),
                          name=os.path.join('GMEMtracking3D_2019_10_14_16_22_2','embryo_track_corr.txt'))
##### load file
print('#'*20+'loading new embryo track (centroid and cm)')
data = np.loadtxt(os.path.join('GMEMtracking3D_2019_10_14_16_22_2','embryo_track_corr.txt'))
centroid = data[:,1:4]
cm = data[:,-3:]

### make corrected animation
reg.make_3d_animation(data_corr,centroid,cm,name='epiboly_corrected.mp4')

plt.show()
