import numpy as np
import os, sys
from scipy.optimize import minimize, root_scalar
from mpl_toolkits.mplot3d import Axes3D
import matplotlib.pyplot as plt
import matplotlib.animation as animation
sys.path.insert(0, 'X:\\Nicola_Gritti\\Repos\\tgmm_quality\\src')
import utils_registration as reg

keys = ['old_id','old_parentid','cell_id','parent_id','lineage','timepoint','X','Y','Z','splitScore']

'''
### not corrected data
'''
### load raw data
print('#'*20+'loading cell tracks generated by TGMM')
data_raw = np.loadtxt(os.path.join('GMEMtracking3D_2019_10_14_16_22_2','cell_track_corr.txt'))
rot_params = np.loadtxt('piv_mat.txt')
data_rot = reg.rotate_piv(data_raw, rot_params, keys)

##### load file
print('#'*20+'loading embryo track (centroid and cm)')
data = np.loadtxt(os.path.join('GMEMtracking3D_2019_10_14_16_22_2','embryo_track_corr.txt'))
centroid = data[:,1:4]
cm = data[:,-3:]

#### make not corrected animation
reg.make_3d_animation(data_rot,centroid,cm,name='epiboly_piv_corrected.mp4',ang=(40,100))

